export const ADDING_INGREDIENT: "ADDING_INGREDIENT" = "ADDING_INGREDIENT";
export const MOVING_INGREDIENT: "MOVING_INGREDIENT" = "MOVING_INGREDIENT";
export const REMOVING_INGREDIENT: "REMOVING_INGREDIENT" = "REMOVING_INGREDIENT";
export const GETTING_BURGER_CONSTRUCTOR: "GETTING_BURGER_CONSTRUCTOR" =
  "GETTING_BURGER_CONSTRUCTOR";
export const MAKING_ORDER: "MAKING_ORDER" = "MAKING_ORDER";
export const CLEARING_ORDER: "CLEARING_ORDER" = "CLEARING_ORDER";
export const MAKING_REJECTED_ORDER: "MAKING_REJECTED_ORDER" =
  "MAKING_REJECTED_ORDER";
export const MAKING_REQUEST_ORDER: "MAKING_REQUEST_ORDER" =
  "MAKING_REQUEST_ORDER";
export const ADDING_BUN: "ADDING_BUN" = "ADDING_BUN";
export const RECALCULATING_AMOUNT: "RECALCULATING_AMOUNT" =
  "RECALCULATING_AMOUNT";
