export const GETTING_INGREDIENTS: "GETTING_INGREDIENTS" = "GETTING_INGREDIENTS";
export const GETTING_REJECTED_INGREDIENTS: "GETTING_REJECTED_INGREDIENTS" =
  "GETTING_REJECTED_INGREDIENTS";
export const GETTING_REQUEST_INGREDIENTS: "GETTING_REQUEST_INGREDIENTS" =
  "GETTING_REQUEST_INGREDIENTS";
